export const AppColors = {
  themePrimaryColor: '#403ADD',
  themeMapColor: '#01b0ff',
  themeMapColorBorder: '#1867d2',
  themeSecondaryMapColor: '#bcbdbf',
  themeSecondarMapBorderColor: '#939497',
  themeBgColor: '#FAFAFB',
  themeTextPrimaryColor: '#5C5C5C',
  themeBtnDisableColor: '#B4AAF2',
  themeBtnHoverColor: '#d8501e',
  themeSeperatorColor: '#e0dbdb',
  themesWhiteColor: '#fff',
  themeBlackColor: '#000',
  textColor: '#3E4958',
  themeCardBorderColor: '#CDCED1',
  themeTextGrayColor: '#B9B9B9',
  themeText2Color: '#74788D',
  themeTextColorNormal: '#3E4958',
  themeIdentityBgColor: '#f4f4f4',
  themePickupDropSearchBg: '#F7F7FC',
  themeNotificationBg: '#F9F9FF',
  themeButtonRed: '#ff0e0e',

};
