export const AppKeys = {
  BASE_URL: 'http://18.144.147.220:3000',
  SECRET_KEY: 'secret',
  API_KEY: 'AIzaSyAcMKbrC6dkmUhq3J7dC439pJ3wV_IBScI',
  LOCAL_NOTIFICATION_CHANNEL_ID : 'LOCAL_NOTIFICATION_CHANNEL_ID',
  LOCAL_NOTIFICATION_CHANNEL_NAME : 'LOCAL_NOTIFICATION_CHANNEL_NAME',
};
